use std::{cell::LazyCell, collections::HashMap};

use crate::{
    standard_library::*, 
    types::ValueType,
    values::{NativeFunction}
};

/// An array of functions and their identifiers, accessible in Carabao code.
/// 
/// Blank identifiers correspond to functions that can only be called implicitly.
pub const GLOBAL_FUNCS: [(&'static str, NativeFunction); 7] = [
    ("", NativeFunction {
        name: "to_str",
        params: &[ValueType::Any],
        ret_type: ValueType::String,
        func: strings::to_string,
    }),
    ("print", NativeFunction {
        name: "print",
        params: &[ValueType::Any],
        ret_type: ValueType::None,
        func: builtins::print,
    }),
    ("println", NativeFunction {
        name: "println",
        params: &[ValueType::Any],
        ret_type: ValueType::None,
        func: builtins::println,
    }),
    ("clock", NativeFunction {
        name: "clock",
        params: &[],
        ret_type: ValueType::Int,
        func: builtins::clock,
    }),
    ("__debug_val", NativeFunction {
        name: "debug_val",
        params: &[ValueType::Any],
        ret_type: ValueType::String,
        func: strings::debug_str,
    }),
    // TODO remove accesible identifiers once
    ("__list_len", NativeFunction {
        name: "list_len",
        // i dont wanna deal with some kind of generic list type
        // actual checking can be done during semantic analysis
        params: &[ValueType::Any],
        ret_type: ValueType::Int,
        func: iterables::list_len,
    }),
    ("__str_len", NativeFunction {
        name: "str_len",
        params: &[ValueType::String],
        ret_type: ValueType::Int,
        func: strings::str_len,
    }),
];

/// Maps static string slices to indices to the global funcs list.
/// 
/// Keys are generated by each native function's internal name,
/// such as `list_len` for the function implicitly called in code like
/// ```
/// new my_list = [/*...*/]
/// my_list.len // this calls list_len()
/// ```
/// Intended for use only during compile time to implicitly load functions,
/// located with their corresponding index in global slots.
pub const BUILTIN_FUNC_INDICES: LazyCell<HashMap<&'static str, usize>> = LazyCell::new(|| {
    let mut map = HashMap::new();
    for (index, (_, func)) in GLOBAL_FUNCS.iter().enumerate() {
        map.insert(func.name,index);
    }
    map
});