use std::{cell::{LazyCell}, collections::HashMap, rc::Rc};

use crate::{
    errors::macros::internal_error, standard_library::*, types::ValueType, values::*
};

pub mod macros {
    macro_rules! val_into {
        ($val: expr => $variant: ident) => {{
            let TypedValue::$variant(val) = $val else {
                crate::errors::macros::internal_error!("{:?} was not {}", $val, stringify!($variant))
            };
            val
        }};
    }

    pub(crate) use val_into;
}

macro_rules! native_func {
    // with accessible identifier
    ($ident_str: expr, $func_ptr: path as func($($params: expr),*) : $ret_type: expr) => {
        ($ident_str, TypedValue::NativeFunc(Rc::new(TypedNativeFunction {
            name: $ident_str,
            params: &[$($params),*],
            ret_type: $ret_type,
            func: $func_ptr,
        })))
    };

    // no accessible identifier or type info, name is for internal use only
    ($ident_str: expr, $func_ptr: path) => {
        ("", TypedValue::NativeFunc(Rc::new(TypedNativeFunction {
            name: $ident_str,
            params: &[],
            ret_type: ValueType::None,
            func: $func_ptr,
        })))
    };
}

/// An array of functions and their identifiers, accessible in Carabao code.
/// 
/// Blank identifiers correspond to functions that can only be called implicitly.
pub const GLOBAL_FUNCS: LazyCell<[(&'static str, TypedValue); 20]> = LazyCell::new(|| {
    use ValueType::*;
    [
        // native functions available to the user in global scope
        // the string arg refers to the identfier & internal name
        native_func!("print",   builtins::print as func(Any): None),
        native_func!("println", builtins::println  as func(Any): None),
        native_func!("clock",   builtins::clock as func(): Int),
        native_func!("str",     iterables::strings::to_string as func(Any): String),
        native_func!("split",   iterables::strings::split as func(String, Char): List(String.into())),

        // ==============================================
        // internal, type-unchecked functions
        // the string is the internal name, not identifier

        native_func!("str_len", iterables::strings::len),
        native_func!("str_concat", iterables::strings::concat),
        native_func!("str_slice", iterables::strings::slice),
        native_func!("str_index_get", iterables::strings::index),
        native_func!("str_cmp", iterables::strings::compare),

        native_func!("list_len",       iterables::lists::len),
        native_func!("list_concat",    iterables::lists::concat),
        native_func!("list_slice",     iterables::lists::slice),
        native_func!("list_index_get", iterables::lists::index_get),
        native_func!("list_index_set", iterables::lists::index_set),
        native_func!("new_list",       iterables::lists::new_list),

        // TODO replace ranges with structs?
        native_func!("new_range", iterables::ranges::new_range),
        native_func!("range_start", iterables::ranges::range_get_start),
        native_func!("range_end", iterables::ranges::range_get_end),

        native_func!("new_obj", misc::objects::new_object),
    ]
});

/// Maps static string slices to indices to the global funcs list.
/// 
/// Keys are generated by each native function's internal name,
/// such as `list_len` for the function implicitly called in code like
/// ```
/// new my_list = [/*...*/]
/// my_list.len // this calls list_len()
/// ```
/// Intended for use only during compile time to implicitly load functions,
/// located with their corresponding index in global slots.
pub const BUILTIN_FUNC_INDICES: LazyCell<HashMap<&'static str, usize>> = LazyCell::new(|| {
    let mut map = HashMap::new();
    for (index, (_ident, val)) in GLOBAL_FUNCS.iter().enumerate() {
        match val {
            TypedValue::NativeFunc(func) => { map.insert(func.name,index); },
            _ => internal_error!("Other builtin entities not supported")
        }
    }
    map
});